[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.12.2"
openzeppelin_access = ">=2.0.0"
openzeppelin_token = ">=2.0.0"
# garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v1.0.1" }

[dev-dependencies]
openzeppelin_utils = ">=2.0.0"
openzeppelin_testing = ">=4.6.0"
snforge_std = ">=0.51.0"

[cairo]
sierra-replace-ids = false
inlining-strategy = 0


[[target.starknet-contract]]
casm = false


[tool.scarb]
allow-prebuilt-plugins = [
	"snforge_std",
] # Avoids the need to install Rust for snforge_std/starknet-foundry

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/_hKu4IgnPgrF8O82GLuYU"
block_id.tag = "latest"

[tool]
panic-backtrace = true
