name: Build Verifiers

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: software-mansion/setup-scarb@v1
              with:
                  scarb-version: "2.15.2"

            - name: Build all verifiers
              run: scarb build
              working-directory: verifiers

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: verifier-artifacts
                  path: verifiers/target/
